/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.test24.loader.dialog;

/**
 *
 * @author Gumerovmn
 */
public class EditPushers extends javax.swing.JFrame {

    /**
     * Creates new form EditPushers
     */
    public EditPushers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPushers = new javax.swing.JScrollPane();
        tablePushers = new javax.swing.JTable();
        buttonDelete = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        textRegNumber = new javax.swing.JTextField();
        panelTypePushers = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxTypePushers = new javax.swing.JComboBox<>();
        textForce = new javax.swing.JTextField();
        textMove = new javax.swing.JTextField();
        textUnclenching = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Регистрационный номер");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 240, 210, 25);

        tablePushers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a1", "be-790", "400", "300", "30"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Рег. номер", "Тип толкателя", "Ном. усилие (кг)", "Ном.ход (мм)", "Врем. разжатия (сек)"
            }
        ));
        scrollPushers.setViewportView(tablePushers);

        getContentPane().add(scrollPushers);
        scrollPushers.setBounds(0, 0, 640, 190);

        buttonDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonDelete.setText("Удалить");
        buttonDelete.setMaximumSize(new java.awt.Dimension(120, 25));
        buttonDelete.setMinimumSize(new java.awt.Dimension(120, 25));
        buttonDelete.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(buttonDelete);
        buttonDelete.setBounds(30, 310, 120, 25);

        buttonEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonEdit.setText("Редактировать");
        getContentPane().add(buttonEdit);
        buttonEdit.setBounds(30, 350, 120, 25);

        buttonAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonAdd.setText("Добавить");
        getContentPane().add(buttonAdd);
        buttonAdd.setBounds(30, 390, 120, 25);

        textRegNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textRegNumber.setText("jTextField1");
        getContentPane().add(textRegNumber);
        textRegNumber.setBounds(410, 240, 220, 25);

        panelTypePushers.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Параметры типа толкателя", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        panelTypePushers.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Тип толкателя");
        panelTypePushers.add(jLabel2);
        jLabel2.setBounds(20, 18, 190, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Усилие на штоке (кг)");
        panelTypePushers.add(jLabel3);
        jLabel3.setBounds(20, 58, 190, 24);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Ход штока (мм)");
        panelTypePushers.add(jLabel4);
        jLabel4.setBounds(20, 88, 190, 24);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Время разжатия (сек)");
        panelTypePushers.add(jLabel5);
        jLabel5.setBounds(20, 118, 190, 24);

        comboBoxTypePushers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboBoxTypePushers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelTypePushers.add(comboBoxTypePushers);
        comboBoxTypePushers.setBounds(220, 14, 190, 30);

        textForce.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textForce.setText("jTextField2");
        panelTypePushers.add(textForce);
        textForce.setBounds(220, 60, 170, 25);

        textMove.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textMove.setText("jTextField3");
        panelTypePushers.add(textMove);
        textMove.setBounds(220, 90, 170, 25);

        textUnclenching.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textUnclenching.setText("jTextField4");
        panelTypePushers.add(textUnclenching);
        textUnclenching.setBounds(220, 120, 170, 25);

        getContentPane().add(panelTypePushers);
        panelTypePushers.setBounds(190, 280, 440, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPushers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPushers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPushers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPushers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPushers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JComboBox<String> comboBoxTypePushers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelTypePushers;
    private javax.swing.JScrollPane scrollPushers;
    private javax.swing.JTable tablePushers;
    private javax.swing.JTextField textForce;
    private javax.swing.JTextField textMove;
    private javax.swing.JTextField textRegNumber;
    private javax.swing.JTextField textUnclenching;
    // End of variables declaration//GEN-END:variables
}
